[package]
name = "mft2bodyfile"
version = "0.1.0"
authors = ["Jan Starke <Jan.Starke@t-systems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mft = "0.5.3"
winstructs = "0.3.0"
anyhow = "1.0.40"
argparse = "0.2.2"
